trigger:
- main

pool:
  vmImage: ubuntu-latest


steps:
- script: echo 'Running Terraform from the custom path...'
  displayName: 'Run Terraform'

- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'id_rsa.pub'
  
- bash: ls $(terraform-working-directory)

- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/backend'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath) '
    backendType: 'azurerm'
    backendServiceArm: 'ARM_Connection'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'Kubernetes_pipeline_IAAC'
    backendAzureRmResourceGroupLocation: 'Central US'
    backendAzureRmStorageAccountName: 'storageaccevapalve123'
    backendAzureRmContainerName: 'tfstatefiles123'
    backendAzureRmKey: 'kubernetes-dev.tfstate'
    allowTelemetryCollection: true
  displayName: 'Kubernetes Cluster pipeline'

